//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PickME.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comment()
        {
            this.userProfiles = new HashSet<userProfile>();
        }
    
        public int commentId { get; set; }
        public string userId { get; set; }
        public int compId { get; set; }
        public System.DateTime dateTime { get; set; }
        public string text { get; set; }
    
        public virtual comp comp { get; set; }
        public virtual userProfile userProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userProfile> userProfiles { get; set; }
    }
}
